//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dlbr.CommonLogin.IdentityModel.Windows.ValidateDLIUserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://commonlogin.ws.dlbr.dk/security/ws/FaultContracts/2012/09")]
    [System.SerializableAttribute()]
    public partial class SecurityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dlbr.CommonLogin.IdentityModel.Windows.ValidateDLIUserService.SecurityFaultReason ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dlbr.CommonLogin.IdentityModel.Windows.ValidateDLIUserService.SecurityFaultReason Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((this.ReasonField.Equals(value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultReason", Namespace="http://commonlogin.ws.dlbr.dk/security/ws/FaultContracts/2012/09")]
    public enum SecurityFaultReason : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNameOrPasswordIncorrect = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordHasExpired = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountDisabled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountLockedOut = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordMustChange = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://commonlogin.ws.dlbr.dk/security/ws/2012/09/DLILogon", ConfigurationName="ValidateDLIUserService.IValidateUser")]
    public interface IValidateUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://commonlogin.ws.dlbr.dk/security/ws/2012/09/DLILogon/IValidateUser/Validate" +
            "DliUser", ReplyAction="http://commonlogin.ws.dlbr.dk/security/ws/2012/09/DLILogon/IValidateUser/Validate" +
            "DliUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dlbr.CommonLogin.IdentityModel.Windows.ValidateDLIUserService.SecurityFault), Action="http://commonlogin.ws.dlbr.dk/security/ws/2012/09/DLILogon/IValidateUser/Validate" +
            "DliUserSecurityFaultFault", Name="SecurityFault", Namespace="http://commonlogin.ws.dlbr.dk/security/ws/FaultContracts/2012/09")]
        void ValidateDliUser(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidateUserChannel : Dlbr.CommonLogin.IdentityModel.Windows.ValidateDLIUserService.IValidateUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateUserClient : System.ServiceModel.ClientBase<Dlbr.CommonLogin.IdentityModel.Windows.ValidateDLIUserService.IValidateUser>, Dlbr.CommonLogin.IdentityModel.Windows.ValidateDLIUserService.IValidateUser {
        
        public ValidateUserClient() {
        }
        
        public ValidateUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ValidateDliUser(string username, string password) {
            base.Channel.ValidateDliUser(username, password);
        }
    }
}
